### ISSUE TITLE
pr-out bot removes labels

### ISSUE THREAD

**Issue by jennysivapalan** [guardian/prout#17]
The pr-out bot removed my label :cry: 

See: https://github.com/guardian/membership-frontend/pull/475
![screen shot 2015-04-15 at 15 55 56](https://cloud.githubusercontent.com/assets/944375/7161694/4bbf618c-e388-11e4-94b2-c89c94cfa5aa.png)

**Comment by rtyley** [comment]
Looks like #40 didn't fix this issue after all? It shouldn't have removed the `commercial` label here:

![image](https://cloud.githubusercontent.com/assets/52038/23455977/8f8f8ab0-fe69-11e6-9edf-bb0de4818c64.png)
Seen at https://github.com/guardian/frontend/pull/15976#event-981558096

**Comment by rtyley** [comment]
Damn, yep, this is definitely still happening :(

![image](https://user-images.githubusercontent.com/52038/39178978-047b9fcc-47ab-11e8-8ac8-6bf35a616b34.png)

https://github.com/guardian/ophan/pull/2751#event-1586495804

**Comment by rtyley** [comment]
Still happening. The most certain way to fix it would be for Prout to avoid using [Set labels](https://docs.github.com/en/rest/reference/issues#set-labels-for-an-issue) (an approach which is currently wiping out labels unrelated to Prout even tho' there's some code that's supposed to stop that), and instead use more GitHub API calls to add and remove the labels it knows it's supposed to be applying, ie with [`Add labels`](https://docs.github.com/en/rest/reference/issues#add-labels-to-an-issue) & [`Remove a label`](https://docs.github.com/en/rest/reference/issues#remove-a-label-from-an-issue)
