### ISSUE TITLE
Heroku template is out of date

### ISSUE THREAD

**Issue by tackley** [guardian/prout#35]
The Heroku template only demands that `PROUT_GITHUB_ACCESS_TOKEN` is specified.

However, looking at conf/application.conf, `GITHUB_APP_CLIENT_ID` and `GITHUB_APP_CLIENT_SECRET` are also required config variables. 

Without specifying these I get a failure on heroku startup:

```
Aug 04 03:02:47 app/web.1:  Oops, cannot start the server. 
Aug 04 03:02:47 app/web.1:  Configuration error: Configuration error[application.conf @ file:/app/target/universal/stage/conf/application.conf: 16: Could not resolve substitution to a value: ${GITHUB_APP_CLIENT_ID}] 
Aug 04 03:02:47 app/web.1:  	at play.api.Configuration$.configError(Configuration.scala:178) 
Aug 04 03:02:47 app/web.1:  	at play.api.Configuration$.load(Configuration.scala:103) 
Aug 04 03:02:47 app/web.1:  	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81) 
Aug 04 03:02:47 app/web.1:  	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:42) 
Aug 04 03:02:47 app/web.1:  	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27) 
Aug 04 03:02:47 app/web.1:  	at play.core.server.ProdServerStart.main(ProdServerStart.scala) 
Aug 04 03:02:47 app/web.1:  Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ file:/app/target/universal/stage/conf/application.conf: 16: Could not resolve substitution to a value: ${GITHUB_APP_CLIENT_ID} 
```

(I suspect this means the readme is out of date too.)

**Comment by rtyley** [comment]
Ah, I added the 'requirement' for those variables with https://github.com/guardian/prout/commit/9d7b69b4a - adding diagnostics for checking whether a repo is properly configured:

![image](https://cloud.githubusercontent.com/assets/52038/17398502/0c7e93a6-5a35-11e6-8c6f-f1d613eb61d4.png)

...I do need to update the readme to cover this stuff, thanks for reminding me.

**Comment by tackley** [comment]
Turns out if I just set them to dummy values the app starts up, though I haven't got the rest set up to see whether it actually works or not.

**Comment by rtyley** [comment]
Yeah, everything apart from the diagnositcs page should work - the diagnostics page is behind GitHub OAuth
